# Choose one environment: local | test | production
env=local

# Base URLs for each environment
base.url.local=http://localhost:8080/uproad
base.url.test=https://uproad.online/uproad

# Email Verify Deep-links for each environment
email.verify.deep.link.local=uproad://emai-verify
email.verify.deep.link.test=https://uproad.online/uproad/api/users/verify

# Forgot Password Deep-links for each environment
forgot.password.deep.link.local=uproad://reset-password
forgot.password.deep.link.test=https://uproad.online/uproad/api/forgotPassword

# Database URLs for each environment
db.link.local=jdbc:sqlite:F:/Prabodh/uproad/testdb.db
db.link.test=jdbc:sqlite:/opt/tomcat/uproad/db/testdb.db

# Optional: email sender name, support contact, etc.
support.email=support@uproad.com